spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loan:
  message: "Welcome to Bank loans related prod APIs "
  contactDetails:
    name: "Pelin Sud - Product Owner"
    email: "pelins@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956